/**
 * @fileoverview gRPC-Web generated client stub for test.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v0.0.0
// source: test/v1/test.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var buf_validate_validate_pb = require('../../buf/validate/validate_pb.js')

var google_api_annotations_pb = require('../../google/api/annotations_pb.js')

var google_api_httpbody_pb = require('../../google/api/httpbody_pb.js')

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js')
const proto = {};
proto.test = {};
proto.test.v1 = require('./test_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.test.v1.AuthServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.test.v1.AuthServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.test.v1.Test,
 *   !proto.google.protobuf.Empty>}
 */
const methodDescriptor_AuthService_SendTest = new grpc.web.MethodDescriptor(
  '/test.v1.AuthService/SendTest',
  grpc.web.MethodType.UNARY,
  proto.test.v1.Test,
  google_protobuf_empty_pb.Empty,
  /**
   * @param {!proto.test.v1.Test} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  google_protobuf_empty_pb.Empty.deserializeBinary
);


/**
 * @param {!proto.test.v1.Test} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.google.protobuf.Empty)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.google.protobuf.Empty>|undefined}
 *     The XHR Node Readable Stream
 */
proto.test.v1.AuthServiceClient.prototype.sendTest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/test.v1.AuthService/SendTest',
      request,
      metadata || {},
      methodDescriptor_AuthService_SendTest,
      callback);
};


/**
 * @param {!proto.test.v1.Test} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.google.protobuf.Empty>}
 *     Promise that resolves to the response
 */
proto.test.v1.AuthServicePromiseClient.prototype.sendTest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/test.v1.AuthService/SendTest',
      request,
      metadata || {},
      methodDescriptor_AuthService_SendTest);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.google.protobuf.Empty,
 *   !proto.test.v1.Test>}
 */
const methodDescriptor_AuthService_GetTest = new grpc.web.MethodDescriptor(
  '/test.v1.AuthService/GetTest',
  grpc.web.MethodType.UNARY,
  google_protobuf_empty_pb.Empty,
  proto.test.v1.Test,
  /**
   * @param {!proto.google.protobuf.Empty} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.test.v1.Test.deserializeBinary
);


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.test.v1.Test)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.test.v1.Test>|undefined}
 *     The XHR Node Readable Stream
 */
proto.test.v1.AuthServiceClient.prototype.getTest =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/test.v1.AuthService/GetTest',
      request,
      metadata || {},
      methodDescriptor_AuthService_GetTest,
      callback);
};


/**
 * @param {!proto.google.protobuf.Empty} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.test.v1.Test>}
 *     Promise that resolves to the response
 */
proto.test.v1.AuthServicePromiseClient.prototype.getTest =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/test.v1.AuthService/GetTest',
      request,
      metadata || {},
      methodDescriptor_AuthService_GetTest);
};


module.exports = proto.test.v1;

